crypto-power/cryptopower

- go.mod
- libwallet/assets/dcr/consensus.go
- libwallet/assets/dcr/decodetx.go
- libwallet/assets/dcr/utils.go
- libwallet/internal/vsp/feepayment.go
- ui/cryptomaterial/collapsible.go
- ui/cryptomaterial/theme.go
- ui/page/components/consensus_list.go
closes https://github.com/crypto-power/cryptopower/issues/17
- Display the latest consensus changes. Version lock was placed on the previous implementation, it been removed now.
- Upgrade the stake dependency v4 to v5
> Display the latest consensus changes

- libwallet/assets/dcr/consensus.go
closes https://github.com/crypto-power/cryptopower/issues/19
Vote choice should be in lowercase
> Use the lowercase of the vote choice

- go.mod
- ui/window.go
Title on Mainnet: 
Without mainnet:
> Display network on the app title if its not on mainnet

- libwallet/assets/dcr/ticket.go
- libwallet/assets/dcr/types.go
- libwallet/assets/dcr/vsp.go
- libwallet/internal/vsp/client.go
- libwallet/internal/vsp/vsp.go
- libwallet/utils/httpclient.go
- ui/page/staking/stake_overview.go
- ui/page/transaction/transaction_details_page.go
Closes https://github.com/crypto-power/cryptopower/issues/43
`KeepReqAlive` params indicates that the upstream caller wants to manage the request closure.
> Read request body only once

- libwallet/politeia.go
- ui/page/governance/proposal_vote_modal.go
> fix crash that occurs when voting

- libwallet/assets/ltc/sync.go
> prevent address discovery from happening each time the app is launched

- ui/page/components/proposal_list.go
- ui/page/components/votebar_widget.go
- ui/page/governance/proposal_details_page.go
Fix #45 
This PR resolve issues with the proposal vote bar not accurately displaying yes and no vote progress.
> fix vote bar yes and no vote progress display bug

- ui/page/components/components.go
Closes https://github.com/crypto-power/cryptopower/issues/56
> Check for lower case asset names

- ui/cryptomaterial/line.go
- ui/cryptomaterial/tab.go
- ui/modal/info_modal.go
- ui/modal/info_modal_layouts.go
- ui/page/exchange/create_order_page.go
- ui/page/root/home_page.go
- ui/page/root/main_page.go
- ui/page/root/trade_page.go
- ui/page/root/wallet_dex_selector_page.go
- ui/page/root/wallet_list.go
- ui/page/root/wallet_selector_page.go
- ui/page/root/wallet_settings_page.go
- ui/page/root/wallet_setup_page.go
- ui/values/dimensions.go
- ui/values/localizable/en.go
- ui/values/strings.go
- ui/window.go
fix #67 
This PR resolves all the issues listed in issue 67
* move dex, trade pages to trade tab
* fix excess padding between top navigation and page content layout
* fix hidden side nav buttons
* fix order page content alignment bug
* add total value info modal etc
> UI layout clean up and bug fix

- ui/page/root/main_page.go
> Makes Hidden balance persist after app is closed

- libwallet/assets/wallet/walletdata/filter.go
- libwallet/utils/config.go
- ui/page/components/components.go
This MR moves Staking entries from the transactions overview tab to the staking activities tab. closes #46
> Show staking events on the staking tab

- ui/page/root/wallet_setup_page.go
> ui: display homepage after successfully creating/restoring wallet

- ui/page/staking/stake_info.go
> page/staking: return early if dcr wallet is not synced

- ui/cryptomaterial/modal.go
- ui/page/components/receive_modal.go
- ui/page/dcrdex/dex_onboarding_page.go
- ui/page/root/home_page.go
- ui/values/dimensions.go
> add receive modal

- libwallet/utils/httpclient.go
Closes #129 
As per the crash logs, the crash was caused by "concurrent map writes". This MR uses a global mutex to lock the `activeAPIs` map during reads and writes.
> libwallet/utils: avoid concurrent map writes

- ui/page/transaction/transaction_details_page.go
> Return early if error is encountered while fetching vsp ticket info

- libwallet/assets/btc/rescan.go
- libwallet/assets/dcr/rescan.go
- libwallet/assets/ltc/rescan.go
- libwallet/assets/wallet/types.go
- listeners/blockrescanprogress.go
> rescan: Add wallet ID to rescan progress.

- ui/page/root/receive_page.go
> change recieve modal title to To

- ui/cryptomaterial/dropdown.go
> ui: fix dropwdown width bug

- ui/page/info/info_page.go
- ui/page/root/main_page.go
- ui/page/seedbackup/backup_instructions.go
- ui/page/seedbackup/save_seed.go
- ui/page/seedbackup/verify_seed.go
Closes #72 
- Fix cancel seed backup that prevented the actual parent window display.
- Fix the password modal cancel bug on the view seed page
https://github.com/crypto-power/cryptopower/assets/57448127/49e6ae8c-7fdb-4c5a-a1a8-f42f2ec73926
> ui: fix seed backup page display

- ui/page/exchange/create_order_page.go
This MR fixes an issue that caused a panic on the create order page due to its uninitialized state after OnNavigatedTo() has been executed but before the page overlay is removed.
This issue might affect other pages that require special initialization and use an overlay.
EDIT: After a brief check, it seems no other page is affected.
Closes #183
> ui: fix panic on create order page

- go.mod
- libwallet/assets_config.go
- libwallet/assets_manager.go
- libwallet/ext/ext_test.go
- libwallet/ext/rate_notification.go
- libwallet/ext/rate_source.go
- libwallet/ext/service.go
- libwallet/ext/signalr.go
- libwallet/ext/types.go
- libwallet/ext/websocket.go
- libwallet/instantswap.go
- ui/page/components/components.go
- ui/page/exchange/create_order_page.go
- ui/page/exchange/order_scheduler_modal.go
- ui/page/root/home_page.go
- ui/page/root/main_page.go
- ui/page/root/overview_page.go
- ui/page/send/page.go
- ui/utils/utils.go
- ui/values/arrays.go
- ui/values/localizable/en.go
- ui/values/strings.go
- ui/values/style.go
https://github.com/crypto-power/cryptopower/assets/57448127/5e4e95b6-00bf-4d35-a47e-a5d6cdf16ae4
Closes #78
> multi: Implement RateSource for exchange rates

- libwallet/assets/dcr/consensus.go
- libwallet/assets_manager.go
- ui/page/components/consensus_list.go
- ui/page/components/treasury_list.go
- ui/page/components/wallet_account_selector.go
- ui/page/governance/consensus_page.go
- ui/page/governance/governance_page.go
- ui/page/governance/proposals_page.go
- ui/page/governance/splash_screen.go
- ui/page/governance/treasury_page.go
- ui/page/root/home_page.go
- ui/page/root/main_page.go
- ui/page/root/wallet_settings_page.go
> Migrate governance UIs to the home page

- LICENSE
Closes #97 
Adds Cryptopower developers to license
> add cryptopower to license

- ui/page/dcrdex/dcrdex_page.go
- ui/page/exchange/create_order_page.go
- ui/page/root/trade_page.go
- ui/values/localizable/en.go
- ui/values/strings.go
> New layout for trade page

- ui/page/root/overview_page.go
> Fix app crash when switching between the wallets tab and overview tab

- ui/page/root/wallet_settings_page.go
Closes #213 
Implements new layout for wallet settings page
> New wallet settings layout

- ui/page/root/overview_page.go
- ui/page/staking/stake_overview.go
- ui/page/transaction/transaction_details_page.go
- ui/page/transaction/transactions_page.go
fix #87 
This PR redirects to the the tx details page when a tx from the overview page is selected.
> implement redirect to tx details page from overview page

- ui/page/root/overview_page.go
Fix #86 
This PR implements redirect to proposals details page when a proposal is selected from the overview page.
> implement redirect to proposal details page

- app/masterpage.go
- app/pagestack.go
- app/window.go
> Rename pageStack.Push to be more intuitive

- ui/load/utils.go
- ui/page/components/components.go
- ui/page/root/home_page.go
- ui/page/root/wallet_list.go
- ui/page/root/wallet_selector_page.go
> format wallet selector layout for mobile

- how-to-build-mobile.md
> add mobile build instructions

- ui/page/start_page.go
> Update users language setting and preferred settings option

- ui/cryptomaterial/slider.go
- ui/page/root/overview_page.go
- ui/values/dimensions.go
- ui/window.go
> Update layout for mixer and slider on overview page

- ui/page/components/coinformat.go
- ui/page/components/coinformat_test.go
- ui/page/staking/stake_info.go
closes #325
does not touch #318
> staking: Fix layout synced check logic.

- ui/cryptomaterial/image.go
- ui/page/root/wallet_settings_page.go
- ui/page/settings/settings_page.go
this PR is rebased off https://github.com/crypto-power/cryptopower/pull/323, i needed some helper functions from #323
closes #280
closes #281
> general settings page and wallets settings page mobile cleanup

- ui/cryptomaterial/clickable.go
- ui/cryptomaterial/clickable_list.go
- ui/page/accounts/accounts_page.go
Closes #276
I think this UI is good enough and should be used on desktops too. Any thoughts?
This PR:
Figma:
> Implement mobile account page

- ui/page/root/overview_page.go
> Update transaction card and staking card on overview page for mobile

- ui/cryptomaterial/dropdown.go
- ui/page/components/order_list.go
- ui/page/components/utils.go
- ui/page/exchange/order_history_page.go
- ui/page/exchange/trade_page.go
- ui/page/root/home_page.go
- ui/page/root/trade_page.go
closes #320 
there's no trade history page for desktop, so i'm adding trade history page for both desktop and mobile via this PR
> trade history page

- ui/page/root/single_wallet_main_page.go
- ui/page/seedbackup/backup_instructions.go
- ui/page/seedbackup/backup_success.go
- ui/page/seedbackup/save_seed.go
- ui/page/seedbackup/verify_seed.go
Resolves #295 
This PR:
- Update all layout mobile and desktop for backup pages
- Fix close backup page not works
> Update layout mobile and desktop for all backup pages

- ui/page/components/asset_selector.go
- ui/page/components/restore_page.go
- ui/page/components/wallet_setup_page.go
- ui/values/localizable/en.go
- ui/values/strings.go
> Update layout create/restore wallet page for desktop and layout

- ui/cryptomaterial/dropdown.go
- ui/cryptomaterial/theme.go
- ui/page/dcrdex/market.go
- ui/page/root/home_page.go
- ui/window.go
> Improve auto closing open dropdowns

- libwallet/instantswap/instantswap.go
- libwallet/instantswap/sync.go
- ui/page/components/order_list.go
- ui/page/exchange/create_order_page.go
- ui/page/exchange/order_history_page.go
- ui/page/root/overview_page.go
- ui/values/localizable/en.go
- ui/values/strings.go
> Update logic filter on trade history page

- config.go
- libwallet/assets_manager.go
- main.go
> Fix error of not being able to open log file

- ui/cryptomaterial/segmented_control.go
- ui/page/components/items_scroll.go
- ui/page/root/single_wallet_main_page.go
- ui/page/send/layout.go
- ui/page/transaction/transactions_page.go
> Update layout wallet main page, update logic segmented control and logic scroll loading

- libwallet/assets/btc/sync.go
- libwallet/assets/ltc/sync.go
May close #357 @JustinBeBoy can you try this out
> Sync: Release write mutex on sync data.

- libwallet/assets/wallet/walletdata/filter.go
- libwallet/utils/config.go
- ui/page/components/components.go
- ui/page/root/overview_page.go
> Show other asset's transactions on the overview page

- dexc/core.go
> Fix app crash when start dex client

- ui/page/root/home_page.go
Closes #386
I think we should follow this pattern (some pages do this already) where an `initPageItems` initializes all dropdowns/segment controls/nav items that use a translated string to ensure the correct translation is displayed.
> Re-translate `HomePage` nav items `OnNavigatedTo`

- libwallet/assets/btc/transactions.go
- libwallet/assets/ltc/transactions.go
- libwallet/assets/wallet/wallet_utils.go
- ui/page/transaction/transactions_page.go
Closes #371 
- Fix wallet tx sort for btc and ltc
- Fix wallet tx sort on the transactions page
> Fix wallet tx sort

- libwallet/internal/loader/config.go
> Fix panic when creating a new wallet dir

- dexc/core.go
- libwallet/assets_manager.go
- ui/page/root/wallet_list.go
- ui/page/settings/settings_page.go
- ui/values/localizable/en.go
- ui/values/strings.go
As requested by @itswisdomagain
> Add button to delete testnet dex data on the settings view

- dexc/core.go
- libwallet/assets/ltc/dex-wallet.go
- libwallet/assets/ltc/wallet.go
- libwallet/assets_manager.go
> Add dex support for Cryptopwer LTC wallet

- libwallet/txhelper/helper.go
- ui/page/transaction/transactions_page.go
- ui/values/localizable/en.go
- ui/values/strings.go
The UI looks different from Figma as this is a desktop-only feature.
UI:
> Add export feature on Crypower Desktop

- ui/page/components/wallet_account_selector.go
- ui/page/exchange/create_order_page.go
- ui/page/receive/receive_page.go
- ui/page/root/wallet_selector_page.go
- ui/page/send/layout.go
- ui/page/send/page.go
- ui/page/send/recipient.go
- ui/page/settings/about_page.go
- ui/page/settings/license_page.go
- ui/page/wallet/single_wallet_main_page.go
- ui/values/localizable/en.go
- ui/values/strings.go
> prevent access to send and receive page content when syncing

- ui/page/dcrdex/dcrdex_page.go
- ui/values/localizable/en.go
- ui/values/strings.go
closes https://github.com/crypto-power/cryptopower/issues/410
> disable dcrdex on mainnet

- ui/cryptomaterial/editor.go
- ui/cryptomaterial/theme.go
- ui/window.go
Resolve #398 
This PR add function listen for user touch events and determine the position relative to the editor. If position outside the editor, will close the keyboard
> Add auto hide softkeyboard for mobile

- libwallet/assets/btc/dex-wallet.go
- libwallet/assets/dcr/dex_wallet.go
As requested by @itswisdomagain
- https://github.com/crypto-power/cryptopower/commit/44e8262847f0d7fce8a7932733cc9560d469db19: Use Decred network backend for `PublishTransaction`.
- https://github.com/crypto-power/cryptopower/commit/7f0493c692cb3ffe5d3b8ed9d8589726d1de9b19: temp fix for chainService.Peers() stalling when attempting login with a btc wallet that isn't connected to any peers
> btc&dcr: Fix dex wallet issues

- ui/page/dcrdex/market.go
As requested by @itswisdomagain
> Display executed orders with active matches as open orders

- libwallet/assets_manager.go
- libwallet/dex_wallets_loader.go
#419 should go in before this.
> decouple AssetsManager from dex wallet constructors

- libwallet/assets/btc/txauthor.go
- libwallet/assets/dcr/txauthor.go
- libwallet/assets/ltc/txauthor.go
- libwallet/assets/wallet/asset_interface.go
- libwallet/assets/wallet/types.go
- libwallet/instantswap.go
- ui/page/exchange/confirm_order_modal.go
- ui/page/governance/proposal_vote_modal.go
- ui/page/privacy/shared_modals.go
- ui/page/root/overview_page.go
- ui/page/send/layout.go
- ui/page/send/manual_coin_selection.go
- ui/page/send/page.go
- ui/page/send/recipient.go
- ui/page/send/send_amount.go
- ui/page/send/send_confirm_modal.go
Resolve #380 
Resolve #407 
Resolve #42
> Allow sending to multiple recipients and fix some bugs

- libwallet/assets/ltc/dex-wallet.go
This PR fixes an issue with LTC `*neutrino.ChainService.Peers()`. The `.Peers()` method may stall, especially if the wallet hasn't started syncing yet. We had a similar fix for BTC but the issue was not noticed earlier for LTC wallets.
EDIT: Other hotfix commits have been moved to https://github.com/crypto-power/cryptopower/pull/449 so this PR can progress quickly.
> hotfix: Fix LTC `*neutrino.ChainService.Peers()` issue

- libwallet/assets/wallet/wallet_config.go
- libwallet/assets/wallet/wallet_shared.go
- libwallet/assets_config.go
- libwallet/assets_manager.go
- libwallet/btc.go
- libwallet/dcr.go
- libwallet/ltc.go
- main.go
- ui/page/start_page.go
> Allow user customize all setting on start page

- libwallet/assets/dcr/sync.go
- libwallet/assets/dcr/syncnotification.go
- ui/page/components/wallet_sync_info.go
- ui/values/localizable/en.go
- ui/values/strings.go
This PR add more process info into sync info
Screenshot:
> Improve sync info

- ui/cryptomaterial/dropdown.go
- ui/cryptomaterial/modal.go
- ui/page/components/components.go
- ui/page/components/wallet_account_selector.go
- ui/page/root/wallet_list.go
- ui/page/root/wallet_selector_page.go
- ui/page/transaction/transactions_page.go
> Update wallet name when it so long

- ui/cryptomaterial/util.go
- ui/page/root/overview_page.go
- ui/page/root/wallet_list.go
- ui/page/root/wallet_selector_page.go
Resolve #474 
Resolve #478 
Screenshot
> update margin page and format balance

- ui/cryptomaterial/editor.go
- ui/load/appinfo.go
- ui/page/components/seed_restore_page.go
- ui/window.go
Resolve #453 
This PR handle keyboard when user taps the bottom Editor of seed list
> Show keyboard on wallet restore page on ios

- README.md
closes https://github.com/crypto-power/website/pull/10
> Add android/ios links to readme

- ui/cryptomaterial/editor.go
- ui/cryptomaterial/linearlayout.go
- ui/load/appinfo.go
- ui/page/components/bottom_nav.go
- ui/page/components/components.go
- ui/page/components/consensus_list.go
- ui/page/receive/receive_page.go
- ui/page/root/home_page.go
- ui/page/root/overview_page.go
- ui/page/send/recipient.go
- ui/values/dimensions.go
Resolve #476 
Resolve #395 
Resolve #482  
Screenshot
> update text size for mobile and desktop version, update error text on Editor layout

- ui/cryptomaterial/editor.go
This PR:
- Fix multiple paste and copy button showing
- Fix title editor not showing
- Fix paste no longer works
> Update menu and fix editor title and hint

- libwallet/assets/dcr/dex_wallet.go
Follow-up PR.
See: https://github.com/crypto-power/cryptopower/pull/438#discussion_r1475873390
> asset/dcr: use connect context for dcr dex wallet

- ui/page/components/items_scroll.go
- ui/page/transaction/transactions_page.go
Resolve #326 
This PR Add new logic for items scroll component
> Update Item scroll component for load more item

- ui/page/components/components.go
- ui/page/receive/receive_page.go
- ui/page/send/layout.go
- ui/page/transaction/transactions_page.go
Resolve #394 
Resolve #414 
**Screenshot**
> fix dropdown and title on overlay

- libwallet/assets/btc/wallet.go
- libwallet/assets/dcr/wallet.go
- libwallet/assets/ltc/wallet.go
- libwallet/assets/wallet/asset_interface.go
- libwallet/assets/wallet/wallet_shared.go
- libwallet/assets/wallet/wallet_utils.go
- libwallet/internal/loader/dcr/loader.go
- libwallet/utils/errors.go
- ui/page/components/wallet_sync_info.go
- ui/page/root/home_page.go
- ui/page/root/overview_page.go
- ui/page/root/wallet_list.go
- ui/page/wallet/single_wallet_main_page.go
- ui/page/wallet/wallet_settings_page.go
- ui/values/localizable/en.go
- ui/values/strings.go
Closes #503 
Same flow as Back Up.
> multi: Add feature to export wallet seed after initial backup

- ui/page/components/wallet_setup_page.go
- ui/page/root/home_page.go
- hide total usd balance if exchange rate is not available
> add top padding for create wallet title

- libwallet/assets/wallet/wallet_shared.go
> fix bug where wallet is asking users to backup an already backed up wallet

- ui/page/components/restore_page.go
- ui/page/components/seed_restore_page.go
> Close seed restore page by default after a successful restore

- libwallet/internal/politeia/politeia_sync.go
- ui/page/components/items_scroll.go
- ui/page/governance/proposals_page.go
Resolve #514 
Resolve #515 
This PR:
- Update logic load proposals on governance page
- Update logic first load transactions on transaction page
- Update logic for search logic on transaction page and governance page
- Update code to fix layout on transaction page and governance page
- Fix scroll bar when change filter on proposal page and governance page
> update logic load proposal and fix loading on transaction page

- libwallet/assets/wallet/wallet_config.go
- libwallet/assets_config.go
- ui/page/exchange/create_order_page.go
- Remove unused db methods
- Refactor
- Rename some db methods
> Multi: Clean up

- ui/page/components/wallet_sync_info.go
closes #535 
multiple goroutines were attempting to write to the same map concurrently, which caused the app to crash with a `fatal error: concurrent map writes`. This PR fixes that
> add a mutex to the write operation on syncprogressinfo

- ui/cryptomaterial/dropdown.go
- ui/page/send/page.go
- ui/page/send/recipient.go
- ui/page/send/send_destination.go
This PR fixed unable focus on the destination address on the send page/modal
> fix unable focus on the destination address on the send page/modal

- ui/page/components/wallet_sync_info.go
> Removed wallet backup button and make the backup warning clickable

- ui/page/components/account_dropdown.go
- ui/page/privacy/manual_mixer_setup_page.go
- ui/page/send/page.go
- ui/page/send/recipient.go
- ui/page/send/send_amount.go
- ui/page/send/send_destination.go
Close #606 
Close #607 
Close #549 
This PR update select wallet/account logic in send page, receive page and some logic in send page
> Update logic wallet and account selector in send page and receive page

- libwallet/assets/dcr/agenda.go
- libwallet/assets/dcr/errors.go
- libwallet/assets/dcr/types.go
- libwallet/assets_manager.go
- libwallet/utils/config.go
- ui/page/governance/consensus_page.go
- ui/page/governance/governance_page.go
- ui/page/governance/proposals_page.go
- ui/page/root/home_page.go
- ui/page/root/overview_page.go
Closes: 
- #591 
This PR following changed:
- Save consensus fetched data to database
- Add ticker to update view periodically, auto Syncing on Proposals and Consensus views  after X min
- Clicking on a proposal from the overview page to go to the Governance proposal view.
> cache consensus fetched data

- ui/page/wallet/single_wallet_main_page.go
- ui/page/wallet/wallet_settings_page.go
Close #614 
This pr redirect user to rescan page after user click to rescan on wallet setting page
> Redirect to rescan page

- ui/page/components/account_dropdown.go
- ui/page/components/wallet_dropdown.go
- ui/page/exchange/create_order_page.go
- ui/page/exchange/order_settings_modal.go
- ui/page/governance/agenda_vote_modal.go
- ui/page/privacy/manual_mixer_setup_page.go
- ui/page/receive/receive_page.go
- ui/page/send/page.go
- ui/page/send/send_amount.go
- ui/page/send/send_confirm_modal.go
- ui/page/send/send_destination.go
- ui/page/staking/stake_modal.go
- ui/values/errors.go
Closed: #618 
This PR changed: 
- fix error in amount input display unclear
- disable send button when amount is less than or equal to zero
- update spenable balance after sending and after transaction is synchronized
- refactor wallet/account dropdown
- check for nil values ​​in several places
> fix the Amount is not updated after sending

- ui/page/info/info_page.go
This PR following changes:
- Move loadTransactions and loadStakes function to run in go routines
- Add load indicator when load transactions/stakes
> fix lagging when open wallet

- ui/cryptomaterial/theme.go
- ui/window.go
This PR has changed:
- disable auto-hide of keyboard when user scrolls
> fix auto hide keyboard when scroll

- ui/cryptomaterial/editor.go
- ui/cryptomaterial/theme.go
- ui/window.go
This PR changed:
- Show menu when tapping after the editor is focused
Tested in Android and IOS
> show menu when tapping after the editor is focused

- ui/page/components/seed_restore_page.go
This PR changed:
- fix app freezes and can't focus to editor on restore page
> fix app freezes and can't focus to editor on restore page

- ui/cryptomaterial/segmented_control.go
- ui/page/privacy/manual_mixer_setup_page.go
- ui/page/security/sign_message_page.go
- ui/page/security/validate_address.go
- ui/page/security/verify_message_page.go
- ui/page/wallet/single_wallet_main_page.go
- ui/values/localizable/en.go
- ui/values/strings.go
closes #653 
closes #657 
closes #540 
closes #651 
closes #642
> fixed a bug where some pages were not scrollable

- ui/page/governance/consensus_page.go
- ui/page/governance/proposals_page.go
- ui/page/governance/treasury_page.go
> hide governance wallet dropdown if only one dcr wallet is available

- ui/window.go
close #659 
This PR resolve back event not work on android
> update handle back button on android

- libwallet/instantswap/instantswap.go
Reverts crypto-power/cryptopower#681
> Revert "automatically create instant.json if it doesn't exist"

- ui/page/dcrdex/market.go
> update dcrdex screen for mobile

- go.mod
- go.sum
- libwallet/assets/btc/utils.go
- libwallet/assets/dcr/utils.go
- libwallet/assets/ltc/utils.go
- libwallet/assets_config.go
- libwallet/utils/config.go
- ui/page/root/home_page.go
- ui/page/root/wallet_selector_page.go
- ui/page/start_page.go
- ui/utils/utils.go
- ui/values/localizable/en.go
- ui/values/strings.go
closes https://github.com/crypto-power/cryptopower/issues/713
> notify user when available disk space is low

- ui/page/root/overview_page.go
This PR hides sections on the overview page with no content to display
> hide sections with no content
