crypto-power/cryptopower

ui/page/components/vsp_selector.go, ui/values/localizable/en.go, ui/values/strings.go
This PR shows the loader UI when loading voting service providers.
Closes #22
=> Show loader when loading VSP

ui/page/privacy/account_mixer_page.go
Closes #51.
Hides mixer status bar when the mixer is not activated
=> Hide progress bar when mixer is not running

ui/cryptomaterial/image.go
closes #94
Unsure of the logic why this is correct, but seems to stretch it out correctly.
=> image: Fix layout width.

ui/page/components/order_list.go, ui/page/root/overview_page.go
=> ui: fix the recent trade display section on overview page

config.go, os.go, os_android.go
closes #37 
Android 11+ only allows creating files in public directories or the app private directory. Using the generic `$HOME/.cryptopower` directory produces a `permission denied` error in android 11+ and prevents the app from initializing.
As an added advantage, using a private directory for the android app ensures the app files are not publicly accessible to other apps.
=> config: use app private directory for android builds

ui/cryptomaterial/slider.go, ui/cryptomaterial/tab.go, ui/page/root/home_page.go, ui/page/root/overview_page.go
Fix #82
This PR implement using live data for the overview sliders.
It also adds a condition to prevent slider widget from adding items repeatedly since Layout() is drawn multiple times per sec.
Testnet is failing when trying to fetch exchange with this error 
```
[ERR] UI: Get "/markets/DCR-USDT/ticker": unsupported protocol scheme ""
2023-09-27 10:02:03.110 [ERR] UI: Get "/markets/DCR-USDT/ticker": unsupported protocol scheme ""
```
Mainnet
=> Use live data for overview Sliders

ui/cryptomaterial/image.go
Scaling large png backgrounds takes up a lot of resources. Add a cache and only create new images when a different size of the same image is requested.
closes #101
=> image: Add layout cache.

ui/page/root/home_page.go
Allows the toggle to start sync.
=> home: Reverse sync toggle logic.

libwallet/assets_manager.go, libwallet/ext/rate_source.go
```      
Config file (/home/upright/.cryptopower/cryptopower.conf) does not exist. Using defaults.
2023-10-23 18:14:18.043 [INF] DLWL: Starting check and remove all dir of deleted wallets....
2023-10-23 18:14:18.043 [ERR] DLWL: can't read DCR root wallet type: open /home/upright/.cryptopower/mainnet/dcr: no such file or directory
2023-10-23 18:14:18.043 [INF] DLWL: Loaded 0 wallets
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x10c2a8e]
goroutine 1 [running]:
github.com/crypto-power/cryptopower/libwallet.(*AssetsManager).GetCurrencyConversionExchange(...)
/home/upright/Documents/cryptopower/libwallet/assets_config.go:141
github.com/crypto-power/cryptopower/libwallet.(*AssetsManager).initRateSource(0xc …
```
=> fix rate source init panic

ui/page/components/coinformat.go, ui/page/components/components.go, ui/page/root/overview_page.go, ui/page/transaction/transactions_page.go, ui/values/dimensions.go, ui/values/localizable/en.go, ui/values/strings.go
This MR adds tx and staking data on the overview page. Closes  #84
=> Add txs and stakes to the overview page

app/masterpage.go, libwallet/assets/dcr/wallet.go, ui/cryptomaterial/slider.go, ui/page/root/home_page.go, ui/values/localizable/en.go, ui/values/strings.go, ui/window.go
Resolve #182 
This PR fix:
- App crash when import only watch-only wallet.
- App crash when click send button
- App crash when import mixed account of watch-only wallet
- App crash when delete wallet.
=> Fix crash when import watch-only wallet and click send button

libwallet/assets_manager.go, ui/page/components/asset_selector.go, ui/page/components/components.go, ui/page/components/restore_page.go, ui/page/components/seed_restore_page.go, ui/page/components/wallet_account_selector.go, ui/page/components/wallet_setup_page.go, ui/page/exchange/create_order_page.go, ui/page/root/wallet_selector_page.go, ui/page/start_page.go, ui/values/localizable/en.go, ui/values/strings.go
This fixes a bug that caused a panic on the create order page and makes it a no-op when an asset with zero wallets is selected as a swap asset.
I'm also wondering if we should prompt the user to create the wallet(1), remove the wallet from the list(2) or just do a no-op(MR).
EDIT: I implemented option (1). 
This required moving some reusable files to the components package. I think it's a step a good direction since DEX is coming and we will also need to be able to create missing wallets from the market/main dex page.
Made a vid of the changes and will upload it soon.
closes #197
=> multi: Fix bugs and enable wallet creation on the create order page

libwallet/assets_manager.go, ui/page/root/wallet_settings_page.go
Closes #206.
After deleting a wallet, we only care about returning to the wallet page(if there are more wallets). This MR fixes a bug that overwrites the "HomePage" display with just the wallet selection page display after deleting a wallet.
=> page/root: display correct wallet page after deleting existing wallet

ui/page/start_page.go
the PR fixes #225.
It prevents the onboarding screens from showing up when wallet is shutting down.
=> fix bug with onboarding screens showing when app is quiting

ui/page/components/coinformat.go, ui/page/components/components.go, ui/page/components/mixer_layout.go, ui/page/info/info_page.go, ui/page/info/sync_status.go, ui/page/root/main_page.go, ui/page/root/overview_page.go, ui/page/transaction/transactions_page.go, ui/values/localizable/en.go, ui/values/strings.go
=> Update info page to include stake activities, Recent tx and mixer running.

ui/page/root/main_page.go
Fix #200 
This PR hides the send and receive tab options when the selected wallet is a watch only wallet.
=> Hide send tab option if wallet is watch only

ui/page/root/home_page.go
closes https://github.com/crypto-power/cryptopower/issues/297
before:
this PR
=> fix mobile buttons showing on desktop

ui/cryptomaterial/icon_gallery.go, ui/cryptomaterial/image.go, ui/page/components/components.go, ui/page/components/order_list.go, ui/page/components/utils.go, ui/page/dcrdex/market.go, ui/page/exchange/cex_splash_page.go, ui/page/exchange/create_order_page.go, ui/page/exchange/exchange_selector.go, ui/page/exchange/order_details_page.go, ui/page/exchange/order_history_page.go, ui/page/root/home_page.go, ui/page/root/overview_page.go, ui/page/root/trade_page.go, ui/values/dimensions.go, ui/window.go
closes #159 
closes #285
closes #314
closes #193 
NB: trade history page and max button functionality would be added via another PR
=> fix cex page for mobile

ui/cryptomaterial/icon_gallery.go, ui/cryptomaterial/progressbar.go, ui/cryptomaterial/slider.go, ui/load/appinfo.go, ui/page/components/components.go, ui/page/components/utils.go, ui/page/components/votebar_widget.go, ui/page/info/info_page.go, ui/page/info/sync_status.go, ui/page/staking/utils.go, ui/page/start_page.go, ui/page/transaction/transaction_details_page.go, ui/values/dimensions.go
- Fix some bugs on the wallet info page
- Refactor the wallet info page and reduce text size (in shared components used by the wallet info page)  for mobile
Closes #270 
Note to reviewers: I currently do not have staking, btc and ltc txs to test with atm. This means the second part of #270 is yet to be verified/fixed but I'm putting this up for review and comments—also, a minor tweak of the mobile wallet info card to improve mobile display is part of this PR. 
This PR:
Figma:
=> Refactor wallet info page and reduce text size in shared componenets for mobile

ui/cryptomaterial/segmented_control.go, ui/cryptomaterial/util.go, ui/page/dcrdex/dex_onboarding_page.go, ui/page/root/overview_page.go
As requested by @itswisdomagain.
- Reduced top inset for segmented controls 
- Reduce the top inset for the overview page to ensure a uniform top inset for all main pages
- Make the whole onboarding page scrollable
Before:
After:
Pages on master with similar top inset:
=> Reduce top inset for segmented controls and light refactor

ui/page/exchange/create_order_page.go, ui/page/exchange/trade_page.go
This diff prevents the master `TradePage` from overriding the current page in `HandleUserInteractions`. 
Closes #234
=> Change display in TradePage.HandleUserInteraction only when the nav tab changes

libwallet/assets/btc/accounts.go, libwallet/assets/btc/wallet.go, libwallet/assets/dcr/accounts.go, libwallet/assets/dcr/wallet.go, libwallet/assets/ltc/accounts.go, libwallet/assets/ltc/wallet.go, libwallet/assets/wallet/types.go, ui/page/accounts/accounts_page.go, ui/page/accounts/btc_account_details_page.go, ui/page/accounts/dcr_account_details_page.go, ui/page/accounts/ltc_account_details_page.go, ui/values/localizable/en.go, ui/values/strings.go
As requested by @itswisdomagain.
- Prevent dcr wallets from returning locked unspent utoxs in `wallet.UnspentOutputs`
- Display the correct locked, immature and spendable amounts on the wallet account page
UI
=> Handle locked coins properly

dexc/core.go, libwallet/assets_manager.go, ui/page/dcrdex/dcrdex_page.go, ui/page/dcrdex/dex_interface.go, ui/page/dcrdex/dex_onboarding_page.go, ui/page/dcrdex/market.go, ui/page/root/home_page.go, ui/page/settings/app_settings_page.go, ui/page/wallet/wallet_settings_page.go, ui/values/localizable/en.go, ui/values/strings.go
This PR removes password requests for an existing dex wallet and adds support for dex wallet pass updates.
=> Remove manual dex wallet unlock during bond posting

app/widgetdisplaypage.go, config.go, libwallet/assets_manager.go, libwallet/utils/httpclient.go, log.go, main.go, ui/load/appconfig.go, ui/load/appinfo.go, ui/page/dcrdex/dcrdex_page.go, ui/page/settings/app_settings_page.go, ui/page/start_page.go, ui/preference/list_preference.go, ui/values/localizable/en.go, ui/values/strings.go, ui/window.go
- Add network type switch to settings page
- Replace --network config arg with network type settings value, default to mainnet
- Show network switch button in start page if current network has no wallets
- Implement switchToTestnetBtn click handler in DEXPage
=> multi: implement in-app network type switch

README.md, config.go, dexc/core.go, libwallet/assets/wallet/types.go, libwallet/assets/wallet/wallet_shared.go, libwallet/assets/wallet/wallet_utils.go, libwallet/assets_manager.go, libwallet/utils/netparams.go, main.go, ui/page/dcrdex/certs.go, ui/page/dcrdex/dex_onboarding_page.go, ui/page/wallet/wallet_settings_page.go
closes #408
It looked like creating separate params was the easiest and least code. The dex simnet uses a combination of simnet and regnets. This pr also allows setting the port for persistant peers.
=> multi: Add dextest network.

libwallet/assets/dcr/syncnotification.go, libwallet/assets/wallet/wallet_shared.go, libwallet/assets_manager.go, ui/cryptomaterial/editor.go, ui/cryptomaterial/theme.go, ui/page/components/wallet_sync_info.go, ui/page/root/home_page.go, ui/page/root/overview_page.go, ui/page/root/wallet_selector_page.go, ui/page/start_page.go, ui/page/wallet/single_wallet_main_page.go, ui/page/wallet/wallet_settings_page.go
closes #445 
closes #458
- fix crash when pasting an empty text into the editor
- add watch only wallet sync card to overview page
- fix hover color for setting options on start page
- fix watch only wallet balance not being accounted for
- show wallet name in the editor while trying to rename wallet
- fix a bug where address discovery was not marked as completed for watch only wallets
=> fix crash when pasting an empty text into the editor

libwallet/assets/btc/rescan.go, libwallet/assets/btc/sync.go, libwallet/assets/btc/txandblocknotifications.go, libwallet/assets/ltc/rescan.go, libwallet/assets/ltc/sync.go, libwallet/assets/ltc/txandblocknotifications.go
Notification from the chain client are only meant for one consumer, and that consumer is btcwallet. Instead receive all notifications from btcwallet.
closes #487, closes #488
=> btc/ltc: Do not use chain client notifications.

ui/modal/create_password_modal.go, ui/modal/create_watch_only_modal.go, ui/modal/info_modal.go, ui/modal/text_input_modal.go, ui/page/accounts/accounts_page.go, ui/page/accounts/btc_account_details_page.go, ui/page/accounts/dcr_account_details_page.go, ui/page/accounts/ltc_account_details_page.go, ui/page/components/restore_page.go, ui/page/components/seed_restore_page.go, ui/page/dcrdex/market.go, ui/page/exchange/confirm_order_modal.go, ui/page/exchange/order_scheduler_modal.go, ui/page/exchange/order_settings_modal.go, ui/page/governance/agenda_vote_modal.go, ui/page/governance/proposal_vote_modal.go, ui/page/governance/treasury_page.go, ui/page/privacy/account_mixer_page.go, ui/page/privacy/manual_mixer_setup_page.go, ui/page/privacy/shared_modals.go, ui/page/root/home_page.go, ui/page/security/sign_message_page.go, ui/page/seedbackup/save_seed.go, ui/page/seedbackup/verify_seed.go, ui/page/send/send_confirm_modal.go, ui/page/settings/app_settings_page.go, ui/page/staking/stake_overview.go, ui/page/start_page.go, ui/page/wallet/wallet_settings_page.go
Issue: Some modals like `InfoModal` , `TextInputModal `, and `CreateWatchOnlyModal` do not show a loading btn when the `positiveButtonClicked` callback is executed. Also it didn't fit the pattern  to have callers `m.SetLoading(false)` when they encounter an error in  the `positiveButtonClicked` callback  when we can do that once the callback returns if need be(we already do `m.SetLoading(true)` before calling the callback).
=> Unexport `modal.SetLoading` and allow modals show loading btn

libwallet/assets/dcr/txindex.go, libwallet/assets/dcr/wallet.go, libwallet/internal/loader/dcr/loader.go
In dcr theres a request for the current wallet inside a db transaction, so if a user closes a wallet during *asset.IndexTransactions() It will get the lock at *dcrLoader.UnloadWallet() but then get stuck at l.db.Close() because it cannot close the db while a transation is taking place. So the request in the transation gets stuck trying to get the lock. If that makes sense.
=> dcr: Avoid freeze inside db transaction.

ui/page/root/home_page.go
Close #533 
This PR fixes the error that when returning to the home page, the Transactions/Governance tab was not activated correctly
**Screenshot**
=> Transactions and governance tab is not came back correctly

libwallet/assets/btc/wallet.go, libwallet/assets/dcr/wallet.go, libwallet/assets/ltc/utils.go, libwallet/assets/ltc/wallet.go, libwallet/assets/wallet/types.go, libwallet/assets/wallet/wallet_shared.go, libwallet/assets/wallet/wallet_utils.go, libwallet/dcr.go, ui/page/components/restore_page.go, ui/page/components/seed_restore_page.go, ui/page/components/utils.go, ui/page/components/wallet_setup_page.go
Close #518 
This PR support 12 and 24 word seed from other wallet, update logic when restore wallet and create wallet
**Screenshot**
The input hex need the dropdown because we need to know the entropy use BIP32 or BIP39
=> Support 12 and 24 word seeds from other wallet

libwallet/assets_config.go, libwallet/ext/rate_source.go, ui/preference/list_preference.go, ui/values/arrays.go
Closes #551 
* Fetch exchange rate option just fetchs the choosen exchange by user and up to 3 times for fetching rate. If all times is failed. So `none` option is choosen
* This mr add change by fetch all other available exchange which is supported
* This mr also remove support for bittrex since bittrex is no longer serving
=> fetch exchange rate api should pick a working default

libwallet/assets/wallet/walletdata/btc_db.go, libwallet/assets/wallet/walletdata/ltc_db.go
Resolved the following error logs that occur during the wallet rescan:
```
2024-07-23 12:31:29.960 [ERR] B-NTR: Could not write filters to filterDB: need batch
2024-07-23 12:34:48.790 [ERR] B-NTR: Could not write filters to filterDB: need batch
2024-07-23 12:42:16.612 [ERR] B-NTR: Could not write filters to filterDB: need batch
2024-07-23 12:46:23.675 [ERR] B-NTR: Could not write filters to filterDB: need batch
2024-07-23 12:59:43.668 [ERR] B-NTR: Could not write filters to filterDB: need batch
```
Implementation of the [BatchDB interface](https://github.com/btcsuite/btcwallet/blob/db3a4a2543bdc7ebc1e992b2f7fd01e4abd257a3/walletdb/interface.go#L243-L250) was an optional requirement but neutrino v0.16.0 implements a [batchWriter functionality](https://github.com/lightninglabs/neutrino/blame …
=> Implement BatchDB Interface in the BTC and LTC WalletData

ui/page/components/restore_page.go, ui/page/components/seed_restore_page.go, ui/page/components/wallet_setup_page.go, ui/page/dcrdex/market.go, ui/page/exchange/create_order_page.go, ui/page/governance/proposal_details_page.go, ui/page/governance/treasury_page.go, ui/page/root/wallet_selector_page.go, ui/page/start_page.go
Closes #595 
This PR enables auto-sync for wallets created from the onboarding screen if it is the first wallet.
=> Enable auto-sync for new wallet on fresh install

ui/cryptomaterial/segmented_control.go, ui/page/root/wallet_selector_page.go, ui/page/wallet/single_wallet_main_page.go
Close #590 
Close #588 
- Updated the wallet detail page to remember the selected tab and navigate to it when the page is revisited
- Updated the Wallets page to track the expanded asset type and expand it on page revisit.
- Update the nav tab on the Wallet page to auto hide/show the left/right scroll button when it is ready in the left-most or right-most position
=> Remember selected tab on the wallet page

ui/page/wallet/single_wallet_main_page.go
Closes: #587 
This resolved:
- Change wallet name in wallet details page to a dropdown to quickly switch wallets
=> Change wallet name in wallet details page to a dropdown

libwallet/assets/btc/sync.go, libwallet/assets/ltc/sync.go, ui/cryptomaterial/switch.go
closed: #621 
this PR following changes:
- Fix app freeze after turn off sync then click back button. Remove unnecessary RWMutex.Rlock().
- Always return false in the Changed function to prevent the user change the switch when the switch is disabled
=> fix app freeze after turn off sync then click back button

ui/page/accounts/dcr_account_details_page.go
This PR adds a new locked coin type (Locked By Tickets) to the account details page, resolving an issue where a user might be confused about why their coins are locked.
IMO, we should hide zero bal fields on this page. esp anything `locked`.
=> ui/page/accounts: list coins locked by ticket separately

ui/page/start_page.go
The main reason for removing this, is to not confuse regular users who most likely don't need the setting right off the bat, it can still be accessed from the settings page
=> remove switch to testnet from add wallet page

ui/page/send/send_destination.go
This PR changed:
- Fixed an issue where the button was disabled when there was only one wallet of the same type
=> Fixed the button was disabled in send page

ui/cryptomaterial/dropdown.go, ui/page/wallet/single_wallet_main_page.go
This PR following changes:
- Refactor dropdown layout
- The dropdown icon in the wallet details page appears to be text so far
=> refactor dropdown layout

ui/page/governance/proposal_vote_modal.go, ui/page/root/home_page.go, ui/page/root/overview_page.go, ui/page/root/wallet_selector_page.go, ui/page/send/layout.go, ui/page/send/page.go, ui/page/send/recipient.go, ui/page/wallet/single_wallet_main_page.go, ui/values/localizable/en.go, ui/values/strings.go
closes #670 
closes #664 
closes #661 
closes #671
=> Send page improvements

go.mod, libwallet/assets/dcr/dex_wallet.go, libwallet/assets/dcr/sync.go, libwallet/assets/dcr/syncnotification.go, libwallet/assets/ltc/wallet.go, libwallet/ext/rate_source.go, libwallet/instantswap.go, ui/page/components/account_dropdown.go, ui/page/dcrdex/market.go, ui/page/exchange/create_order_page.go, ui/page/exchange/order_details_page.go, ui/page/exchange/order_scheduler_modal.go, ui/page/exchange/order_settings_modal.go, ui/values/localizable/en.go, ui/values/strings.go
This PR resolves a handful of bugs, code improvements on the CEX page, and minor dex improvements.
- [assets/dcr: fix panic when sync is not active](https://github.com/crypto-power/cryptopower/commit/74405a82a3bc723f10e093c339727fd07024be82): This issue has been recurring but the fix has been included in this PR.
- [libwallet: rework instantswap feature](https://github.com/crypto-power/cryptopower/commit/3e77b327aebb2132f3eb32ec0d860c8d7320d1ca)
- [exchange: fix order detail page panic when fetching order returns an error](https://github.com/crypto-power/cryptopower/commit/9e39082c88bdf5fcf7fcfa802269eea08cb31199)
- [multi: Fix CEX page](https://github.com/crypto-power/cryptopower/commit/660ce5f8bb102d0e6e074cab4e718aed2ad283f2)
- Fix asset selector dropdown
- Fix asset amount input
- Fix …
=> multi: Bug fixes and code improvements

ui/page/info/info_page.go, ui/page/root/overview_page.go, ui/page/transaction/transactions_page.go
=> add View All button in overview page to see the full list

dexc/core.go, libwallet/assets_manager.go, ui/page/dcrdex/dcrdex_page.go, ui/page/root/home_page.go, ui/page/root/migrate_page.go, ui/page/start_page.go, ui/window.go
> @dreacot: I noticed dex gets initialized immediately after the app is opened And not when the start trading button is clicked and the splash screen for dex doesn’t show because it’s initialized on the homepage.
Dex will still be initialized for existing dex users when they open the app but no longer for new users.
=> Allow users decide dexc first time initialization

.github/workflows/go.yml
[The Ubuntu 20.04 Actions runner image will begin deprecation on 2025-02-01 and will be fully unsupported by 2025-04-15](https://github.com/actions/runner-images/issues/11101#top)
=> update ubuntu 20.04 to 24.04

ui/page/start_page.go
closes #742 
fixed rendering issue on create wallet button for small devices
=> Added a media query fix for when the device height is less than 600.
